DROP TABLE IF EXISTS `CUSTOMER`;
DROP TABLE IF EXISTS `SELLER`;
DROP TABLE IF EXISTS `PRODUCT`;
DROP TABLE IF EXISTS `CATEGORY`;
DROP TABLE IF EXISTS `PRODUCT_CATEGORY`;
DROP TABLE IF EXISTS `ORDER`;
DROP TABLE IF EXISTS `ADDRESS`;
DROP TABLE IF EXISTS `ORDER_ITEM`;
DROP TABLE IF EXISTS `PAYMENT`;
DROP TABLE IF EXISTS `DELIVERY`;
DROP TABLE IF EXISTS `WISHLIST`;
DROP TABLE IF EXISTS `REVIEW`;


CREATE TABLE `CUSTOMER`
(
    `CUSTOMER_ID`  BIGINT PRIMARY KEY AUTO_INCREMENT,
    `EMAIL`        VARCHAR(255) UNIQUE NOT NULL,
    `PASSWORD`     VARCHAR(255)        NOT NULL,
    `NAME`         VARCHAR(20)         NOT NULL,
    `PHONE_NUMBER` VARCHAR(20) UNIQUE  NOT NULL,
    `CREATED_DATE` DATETIME            NOT NULL,
    `UPDATED_DATE` DATETIME            NOT NULL
);



CREATE TABLE `SELLER`
(
    `SELLER_ID`    BIGINT PRIMARY KEY AUTO_INCREMENT,
    `EMAIL`        VARCHAR(255)       NOT NULL,
    `PASSWORD`     VARCHAR(255)       NOT NULL,
    `NAME`         VARCHAR(20)        NOT NULL,
    `STORE_NAME`   VARCHAR(20)        NOT NULL,
    `PHONE_NUMBER` VARCHAR(20) UNIQUE NOT NULL,
    `CREATED_DATE` DATETIME           NOT NULL,
    `UPDATED_DATE` DATETIME           NOT NULL
);

CREATE TABLE `PRODUCT`
(
    `PRODUCT_ID`     BIGINT PRIMARY KEY AUTO_INCREMENT,
    `SELLER_ID`      BIGINT       NOT NULL,
    `NAME`           VARCHAR(255) NOT NULL,
    `DESCRIPTION`    VARCHAR(255) NOT NULL,
    `PRICE` DOUBLE NOT NULL,
    `STOCK_QUANTITY` BIGINT       NOT NULL,
    `IMAGE_URL`      VARCHAR(255) NOT NULL,
    `CREATED_DATE`   DATETIME     NOT NULL,
    `UPDATED_DATE`   DATETIME     NOT NULL
);

CREATE TABLE `CATEGORY`
(
    `CATEGORY_ID`  BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PARENT_ID`    BIGINT,
    `DEPTH`        BIGINT              NOT NULL,
    `NAME`         VARCHAR(255) UNIQUE NOT NULL,
    `CREATED_DATE` DATETIME            NOT NULL,
    `UPDATED_DATE` DATETIME            NOT NULL
);

CREATE TABLE `PRODUCT_CATEGORY`
(
    `PRODUCT_ID`   BIGINT,
    `CATEGORY_ID`  BIGINT,
    `CREATED_DATE` DATETIME NOT NULL,
    `UPDATED_DATE` DATETIME NOT NULL,
    PRIMARY KEY (`PRODUCT_ID`, `CATEGORY_ID`)
);

CREATE TABLE `ORDER`
(
    `ORDER_ID`     BIGINT PRIMARY KEY AUTO_INCREMENT,
    `CUSTOMER_ID`  BIGINT   NOT NULL,
    `ORDER_DATE`   DATETIME NOT NULL,
    `STATUS`       ENUM ('PENDING', 'SHIPPED', 'IN_TRANSIT', 'COMPLETED', 'CANCELED') NOT NULL,
    `CREATED_DATE` DATETIME NOT NULL,
    `UPDATED_DATE` DATETIME NOT NULL
);

CREATE TABLE `ADDRESS`
(
    `ADDRESSID`            BIGINT PRIMARY KEY AUTO_INCREMENT,
    `CUSTOMER_ID`          BIGINT      NOT NULL,
    `RECEIPT_NAME`         VARCHAR(20) NOT NULL,
    `RECEIPT_PHONE_NUMBER` VARCHAR(20) NOT NULL,
    `REGION`               VARCHAR(50) NOT NULL,
    `CITY`                 VARCHAR(50) NOT NULL,
    `TOWN`                 VARCHAR(50) NOT NULL,
    `STREET`               VARCHAR(50) NOT NULL,
    `ZIP_CODE`             VARCHAR(50) NOT NULL,
    `DETAIL`               VARCHAR(50) NOT NULL,
    `CREATED_DATE`         DATETIME    NOT NULL,
    `UPDATED_DATE`         DATETIME    NOT NULL
);

CREATE TABLE `ORDER_ITEM`
(
    `ORDER_ITEM_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `ORDER_ID`      BIGINT   NOT NULL,
    `PRODUCT_ID`    BIGINT   NOT NULL,
    `QUANTITY`      BIGINT   NOT NULL,
    `PRICE_PER_ITEM` DOUBLE NOT NULL,
    `CREATED_DATE`  DATETIME NOT NULL,
    `UPDATED_DATE`  DATETIME NOT NULL
);

CREATE TABLE `PAYMENT`
(
    `PAYMENT_ID`     BIGINT PRIMARY KEY AUTO_INCREMENT,
    `ORDER_ID`       BIGINT UNIQUE NOT NULL,
    `AMOUNT` DOUBLE NOT NULL,
    `PAYMENT_METHOD` ENUM ('CREDIT_CARD', 'KAKAOPAY', 'NAVERPAY', 'TOSSPAY') NOT NULL,
    `PAYMENT_DATE`   DATETIME      NOT NULL,
    `PAYMENT_STATUS` ENUM ('WAITING', 'COMPLETED', 'FAILED', 'REFUNDED') NOT NULL,
    `CREATED_DATE`   DATETIME      NOT NULL,
    `UPDATED_DATE`   DATETIME      NOT NULL
);


CREATE TABLE `DELIVERY`
(
    `DELIVERY_ID`     BIGINT PRIMARY KEY AUTO_INCREMENT,
    `ORDER_ID`        BIGINT UNIQUE NOT NULL,
    `DELIVERY_NOTES`  VARCHAR(255)   NOT NULL,
    `DELIVERY_STATUS` ENUM ('PENDING', 'SHIPPED', 'IN_TRANSIT', 'DELIVERED', 'CANCELED') NOT NULL,
    `TRACKING_NUMBER` VARCHAR(255)   NOT NULL,
    `SHIPMENT_DATE`   DATETIME       NOT NULL,
    `ESTIMATED_DATE`  DATETIME       NOT NULL,
    `ARRIVAL_DATE`    DATETIME       NOT NULL,
    `CREATED_DATE`    DATETIME       NOT NULL,
    `UPDATED_DATE`    DATETIME       NOT NULL
);

CREATE TABLE `REVIEW`
(
    `REVIEW_ID`    BIGINT PRIMARY KEY AUTO_INCREMENT,
    `CUSTOMER_ID`  BIGINT  NOT NULL,
    `PRODUCT_ID`   BIGINT  NOT NULL,
    `CONTENT`      TEXT     NOT NULL,
    `RATING`       INT      NOT NULL,
    `CREATED_DATE` DATETIME NOT NULL,
    `UPDATED_DATE` DATETIME NOT NULL
);


CREATE TABLE `WISHLIST`
(
    `WISHLIST_ID`  BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PRODUCT_ID`   BIGINT,
    `CUSTOMER_ID`  BIGINT,
    `CREATED_DATE` DATETIME NOT NULL,
    `UPDATED_DATE` DATETIME NOT NULL
);