DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER
(
    ID BIGINT AUTO_INCREMENT,
    EMAIL        VARCHAR(255),
    PASSWORD     VARCHAR(255),
    NAME         VARCHAR(20),
    PHONE_NUMBER VARCHAR(20),
    PRIMARY KEY (ID)
);