server:
  port: 8081

spring:
  profiles:
    default: test

  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE

---

spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/joyMall;MODE=MYSQL;
    username: sa
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

kakao-pay:
  host: https://open-api.kakaopay.com
  cid: TC0ONETIME
  secret-key: SECRET_KEY DEV65C1FE356C03E6C6DDE53FB94027B73AC7DE2

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/joyMall;
    username: sa
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

kakao-pay:
  host: https://open-api.kakaopay.com
  cid: TC0ONETIME
  secret-key: SECRET_KEY DEV65C1FE356C03E6C6DDE53FB94027B73AC7DE2