server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/joyMall;
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
#      data-locations: classpath:db/data.sql

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE