server:
  port: 8081

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:test}

  jackson:
    default-property-inclusion: non_null

---

spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/joyMall;MODE=MYSQL;
    username: sa
    password:

  data:
    redis:
      host: localhost
      port: 6379


  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

kakao-pay:
  host: https://open-api.kakaopay.com
  cid: ${KAKAO_PAY_CID}
  secret-key: ${KAKAO_PAY_CID_SECRET_KEY}

logging:
  level:
    org:
      springframework:
        jdbc:
          core: trace

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/joyMall;
    username: sa
    password:

  data:
    redis:
      host: localhost
      port: 6379

  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

kakao-pay:
  host: https://open-api.kakaopay.com
  cid: ${KAKAO_PAY_CID}
  secret-key: ${KAKAO_PAY_CID_SECRET_KEY}

logging:
  level:
    org:
      springframework:
        jdbc:
          core: debug

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JOY_MALL_DB_URL}
    username: ${JOY_MALL_DB_USER}
    password: ${JOY_MALL_DB_PASSWORD}

  data:
    redis:
      host: ${JOY_MALL_REDIS_URL}
      port: 6379

kakao-pay:
  host: https://open-api.kakaopay.com
  cid: ${KAKAO_PAY_CID}
  secret-key: ${KAKAO_PAY_CID_SECRET_KEY}

logging:
  level:
    org:
      springframework:
        jdbc:
          core: debug